### PR TITLE
Bump LHW

### PR DESCRIPTION
**Pull request by aaronjwood**
This pulls in https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/232 along with a few other things that have been added recently.

### CODE REVIEW

**Comment by aaronjwood** [comment]
Bleh, didn't expect LHW to break your stuff. Guess this needs a little more work.

**Comment by nickbabcock** [comment]
No worries. Looks like a new hardware type was added to LHW (AeroCool), which will need an entry in OhmGraphite's `Translation.cs`. The tests may seem a bit finicky to run if you're trying to run them locally (the tests with an "integration" category require outside action to setup properly, so only the unmarked tests will run in isolation)

**Comment by aaronjwood** [comment]
Got it, thanks!

**Comment by nickbabcock** [comment]
This has been included in the release of v0.14.0. Try it out and let me know if you're still seeing problems.

**Pull request merged**
